name	'inkblot/network'
version '0.0.1'
source	'git://github.com/inkblot/puppet-network'
author	'inkblot'
license	'Apache 2.0'
summary 'Network routes and interfaces'
description 'A Puppet module to configure network routes and interfaces'
project_page 'https://github.com/inkblot/puppet-network'

dependency 'adrien/filemapper', '1.1.3'
